ARG NODE_BASE_IMAGE=mirror.gcr.io/library/node:18-alpine
ARG NGINX_BASE_IMAGE=mirror.gcr.io/library/nginx:1.27-alpine

FROM ${NODE_BASE_IMAGE} AS build
WORKDIR /web
COPY web/package*.json ./
RUN npm install --prefer-offline --no-audit --progress=false
COPY web .
RUN npm run build

FROM ${NGINX_BASE_IMAGE} AS runtime
WORKDIR /usr/share/nginx/html
COPY --from=build /web/dist .
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
